/*
  # 多租戶改造（第一步）：新增 facilities 院舍表及各表 facility_id 欄位

  目的：為多租戶改造建立 schema 基礎。

  1. 新建 facilities 院舍表，並以 id = 1 作為現有資料的預設院舍。
  2. user_profiles（員工）及院舍級資源表加 facility_id 並回填 1。
  3. 院友主表加 facility_id（tenant 邊界根），所有院友級資料表加冗余
     facility_id，並以 BEFORE INSERT trigger 由院友主表自動填入，
     現有前端 db 函式無需修改。
  4. 共用參考資料表（藥物資料庫、問題庫、範本等）完全不加欄位。
  5. 本 migration 不處理 RLS（developer 跨院舍等於 P2 處理）。

  全部使用 IF NOT EXISTS / IF EXISTS 防重跑；不 DROP 任何現有物件、
  不修改任何現有欄位。
*/

-- ============================================================
-- 1. 院舍主表 facilities
-- ============================================================

CREATE TABLE IF NOT EXISTS facilities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE facilities IS '院舍（租戶）主表；多租戶改造的 tenant 邊界';
COMMENT ON COLUMN facilities.id IS '院舍編號';
COMMENT ON COLUMN facilities.name IS '院舍名稱';
COMMENT ON COLUMN facilities.is_active IS '是否啟用';
COMMENT ON COLUMN facilities.created_at IS '建立時間';

-- 現有全部資料歸屬 facility 1；正式名稱之後在 facility_settings 修改
INSERT INTO facilities (id, name) VALUES (1, '安老院舍')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 2. 員工表 user_profiles
-- ============================================================

ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_profiles SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_profiles.facility_id IS '員工歸屬院舍';

-- ============================================================
-- 3. 院友主表（tenant 邊界根）
-- ============================================================

ALTER TABLE "院友主表" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "院友主表" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "院友主表".facility_id IS '院友歸屬院舍；多租戶 tenant 邊界根';

-- ============================================================
-- 4. 院舍級資源表（加 facility_id、回填 1；無院友連結，不設 trigger）
-- ============================================================

ALTER TABLE stations ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE stations SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN stations.facility_id IS '站點歸屬院舍';

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE rooms SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN rooms.facility_id IS '房間歸屬院舍';

ALTER TABLE beds ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE beds SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN beds.facility_id IS '床位歸屬院舍';

ALTER TABLE station_shift_settings ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE station_shift_settings SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN station_shift_settings.facility_id IS '更次設定歸屬院舍';

ALTER TABLE user_shift_assignments ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_shift_assignments SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_shift_assignments.facility_id IS '員工更次分配，冗余欄位由員工歸屬院舍派生';

ALTER TABLE "到診排程主表" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "到診排程主表" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "到診排程主表".facility_id IS '到診排程歸屬院舍';

ALTER TABLE doctor_visit_schedule ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE doctor_visit_schedule SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN doctor_visit_schedule.facility_id IS '到診醫生檔期歸屬院舍';

ALTER TABLE facility_settings ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE facility_settings SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN facility_settings.facility_id IS '院舍設定歸屬院舍；每院舍一列（單例拆分於 P5 開通頁面階段完整處理）';

ALTER TABLE fee_items ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE fee_items SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN fee_items.facility_id IS '收費項目歸屬院舍';

ALTER TABLE user_absence_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_absence_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_absence_records.facility_id IS '員工缺勤記錄，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_annual_leave_details ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_annual_leave_details SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_annual_leave_details.facility_id IS '員工年假明細，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_balance_adjustments ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_balance_adjustments SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_balance_adjustments.facility_id IS '員工假期結餘調整，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_employment_details ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_employment_details SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_employment_details.facility_id IS '員工僱傭詳情，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_leave_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_leave_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_leave_records.facility_id IS '員工請假記錄，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_ocr_prompts ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_ocr_prompts SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_ocr_prompts.facility_id IS '員工 OCR 提示設定，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_public_holiday_details ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_public_holiday_details SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_public_holiday_details.facility_id IS '員工公眾假期明細，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_rest_day_details ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_rest_day_details SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_rest_day_details.facility_id IS '員工休息日明細，冗余欄位由員工歸屬院舍派生';

ALTER TABLE user_permissions ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE user_permissions SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN user_permissions.facility_id IS '員工權限授予，冗余欄位由員工歸屬院舍派生';

-- 以下兩表無院友連結，歸類為院舍級（backfill 1），保持日後按院舍拆分的可能性
ALTER TABLE daily_system_tasks ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE daily_system_tasks SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN daily_system_tasks.facility_id IS '每日系統工作歸屬院舍（無院友連結）';

ALTER TABLE emergency_operation_log ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE emergency_operation_log SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN emergency_operation_log.facility_id IS '緊急操作日誌歸屬院舍（無院友連結）';

-- ============================================================
-- 5. 院友級資料表（加 facility_id、回填 1，由 trigger 自動維護）
-- ============================================================

ALTER TABLE "健康監測記錄" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "健康監測記錄" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "健康監測記錄".facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE "覆診安排主表" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "覆診安排主表" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "覆診安排主表".facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE "看診院友細項" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "看診院友細項" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "看診院友細項".facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE hospital_episodes ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE hospital_episodes SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN hospital_episodes.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE medication_workflow_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE medication_workflow_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN medication_workflow_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE wounds ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE wounds SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN wounds.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE prescription_activity_log ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE prescription_activity_log SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN prescription_activity_log.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE hospital_outreach_record_history ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE hospital_outreach_record_history SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN hospital_outreach_record_history.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE vaccination_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE vaccination_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN vaccination_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE cgat_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE cgat_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN cgat_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE diaper_change_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE diaper_change_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN diaper_change_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE hygiene_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE hygiene_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN hygiene_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE diaper_usage_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE diaper_usage_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN diaper_usage_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_admission_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_admission_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_admission_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patrol_rounds ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patrol_rounds SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patrol_rounds.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_notes ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_notes SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_notes.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_logs ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_logs SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_logs.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_tube_care_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_tube_care_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_tube_care_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE care_plans ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE care_plans SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN care_plans.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE intake_output_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE intake_output_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN intake_output_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE rehab_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE rehab_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN rehab_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE meal_guidance ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE meal_guidance SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN meal_guidance.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE bed_transfer_log ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE bed_transfer_log SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN bed_transfer_log.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE wound_assessments ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE wound_assessments SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN wound_assessments.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE incident_reports ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE incident_reports SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN incident_reports.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE health_assessments ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE health_assessments SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN health_assessments.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_fee_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_fee_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_fee_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE annual_health_checkups ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE annual_health_checkups SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN annual_health_checkups.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE position_change_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE position_change_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN position_change_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_health_tasks ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_health_tasks SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_health_tasks.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE diagnosis_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE diagnosis_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN diagnosis_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE infection_control_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE infection_control_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN infection_control_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_restraint_assessments ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_restraint_assessments SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_restraint_assessments.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE new_medication_prescriptions ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE new_medication_prescriptions SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN new_medication_prescriptions.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_activity_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_activity_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_activity_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_care_tabs ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_care_tabs SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_care_tabs.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE hospital_outreach_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE hospital_outreach_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN hospital_outreach_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_evening_care_plans ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_evening_care_plans SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_evening_care_plans.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

-- patient_id 可為 NULL（user_id 為主的員工偏好設定列），NULL 時 facility_id 保持 NULL（全院舍共用）
ALTER TABLE medication_workflow_settings ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE medication_workflow_settings SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN medication_workflow_settings.facility_id IS '冗余欄位：由院友歸屬院舍派生；patient_id 為 NULL 的列代表全院舍共用，facility_id 保持 NULL';

ALTER TABLE restraint_observation_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE restraint_observation_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN restraint_observation_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE patient_contacts ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE patient_contacts SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN patient_contacts.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE deleted_health_records ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE deleted_health_records SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN deleted_health_records.facility_id IS '冗余欄位：由院友歸屬院舍自動填入（INSERT trigger）';

-- 經中間表連到院友的院友級資料表
ALTER TABLE care_plan_problems ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE care_plan_problems SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN care_plan_problems.facility_id IS '冗余欄位：經 care_plan_id 由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE care_plan_nursing_needs ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE care_plan_nursing_needs SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN care_plan_nursing_needs.facility_id IS '冗余欄位：經 care_plan_id 由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE episode_events ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE episode_events SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN episode_events.facility_id IS '冗余欄位：經 episode_id 由院友歸屬院舍自動填入（INSERT trigger）';

ALTER TABLE "到診院友_看診原因" ADD COLUMN IF NOT EXISTS facility_id integer REFERENCES facilities(id);
UPDATE "到診院友_看診原因" SET facility_id = 1 WHERE facility_id IS NULL;
COMMENT ON COLUMN "到診院友_看診原因".facility_id IS '冗余欄位：經細項id由院友歸屬院舍自動填入（INSERT trigger）';

-- ============================================================
-- 6. 共用 trigger function 及各院友級表 trigger
--
-- TG_ARGV[0] 為 SQL 表達式，以 $1 代表 NEW（觸發列），回傳院友 id。
-- NEW.facility_id 已有值、院友欄位為 NULL 或找不到院友時保持原值，不報錯。
-- ============================================================

CREATE OR REPLACE FUNCTION set_facility_id_from_patient()
RETURNS trigger AS $func$
DECLARE
  v_patient_id integer;
BEGIN
  IF NEW.facility_id IS NOT NULL THEN
    RETURN NEW;
  END IF;
  EXECUTE format('SELECT %s', TG_ARGV[0]) INTO v_patient_id USING NEW;
  IF v_patient_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT facility_id INTO NEW.facility_id
  FROM "院友主表"
  WHERE "院友id" = v_patient_id;
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_facility_id_from_patient() IS '院友級資料表 INSERT 時由院友主表自動填入 facility_id；TG_ARGV[0] 為回傳院友 id 的 SQL 表達式（$1 = NEW）';

-- 院友欄位為 patient_id 的表
DROP TRIGGER IF EXISTS trg_set_facility_hospital_episodes ON hospital_episodes;
CREATE TRIGGER trg_set_facility_hospital_episodes BEFORE INSERT ON hospital_episodes
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_medication_workflow_records ON medication_workflow_records;
CREATE TRIGGER trg_set_facility_medication_workflow_records BEFORE INSERT ON medication_workflow_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_wounds ON wounds;
CREATE TRIGGER trg_set_facility_wounds BEFORE INSERT ON wounds
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_prescription_activity_log ON prescription_activity_log;
CREATE TRIGGER trg_set_facility_prescription_activity_log BEFORE INSERT ON prescription_activity_log
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_hospital_outreach_record_history ON hospital_outreach_record_history;
CREATE TRIGGER trg_set_facility_hospital_outreach_record_history BEFORE INSERT ON hospital_outreach_record_history
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_vaccination_records ON vaccination_records;
CREATE TRIGGER trg_set_facility_vaccination_records BEFORE INSERT ON vaccination_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_cgat_records ON cgat_records;
CREATE TRIGGER trg_set_facility_cgat_records BEFORE INSERT ON cgat_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_diaper_change_records ON diaper_change_records;
CREATE TRIGGER trg_set_facility_diaper_change_records BEFORE INSERT ON diaper_change_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_hygiene_records ON hygiene_records;
CREATE TRIGGER trg_set_facility_hygiene_records BEFORE INSERT ON hygiene_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_diaper_usage_records ON diaper_usage_records;
CREATE TRIGGER trg_set_facility_diaper_usage_records BEFORE INSERT ON diaper_usage_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_admission_records ON patient_admission_records;
CREATE TRIGGER trg_set_facility_patient_admission_records BEFORE INSERT ON patient_admission_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patrol_rounds ON patrol_rounds;
CREATE TRIGGER trg_set_facility_patrol_rounds BEFORE INSERT ON patrol_rounds
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_notes ON patient_notes;
CREATE TRIGGER trg_set_facility_patient_notes BEFORE INSERT ON patient_notes
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_logs ON patient_logs;
CREATE TRIGGER trg_set_facility_patient_logs BEFORE INSERT ON patient_logs
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_tube_care_records ON patient_tube_care_records;
CREATE TRIGGER trg_set_facility_patient_tube_care_records BEFORE INSERT ON patient_tube_care_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_care_plans ON care_plans;
CREATE TRIGGER trg_set_facility_care_plans BEFORE INSERT ON care_plans
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_intake_output_records ON intake_output_records;
CREATE TRIGGER trg_set_facility_intake_output_records BEFORE INSERT ON intake_output_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_rehab_records ON rehab_records;
CREATE TRIGGER trg_set_facility_rehab_records BEFORE INSERT ON rehab_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_meal_guidance ON meal_guidance;
CREATE TRIGGER trg_set_facility_meal_guidance BEFORE INSERT ON meal_guidance
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_bed_transfer_log ON bed_transfer_log;
CREATE TRIGGER trg_set_facility_bed_transfer_log BEFORE INSERT ON bed_transfer_log
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_wound_assessments ON wound_assessments;
CREATE TRIGGER trg_set_facility_wound_assessments BEFORE INSERT ON wound_assessments
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_incident_reports ON incident_reports;
CREATE TRIGGER trg_set_facility_incident_reports BEFORE INSERT ON incident_reports
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_health_assessments ON health_assessments;
CREATE TRIGGER trg_set_facility_health_assessments BEFORE INSERT ON health_assessments
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_fee_records ON patient_fee_records;
CREATE TRIGGER trg_set_facility_patient_fee_records BEFORE INSERT ON patient_fee_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_annual_health_checkups ON annual_health_checkups;
CREATE TRIGGER trg_set_facility_annual_health_checkups BEFORE INSERT ON annual_health_checkups
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_position_change_records ON position_change_records;
CREATE TRIGGER trg_set_facility_position_change_records BEFORE INSERT ON position_change_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_health_tasks ON patient_health_tasks;
CREATE TRIGGER trg_set_facility_patient_health_tasks BEFORE INSERT ON patient_health_tasks
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_diagnosis_records ON diagnosis_records;
CREATE TRIGGER trg_set_facility_diagnosis_records BEFORE INSERT ON diagnosis_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_infection_control_records ON infection_control_records;
CREATE TRIGGER trg_set_facility_infection_control_records BEFORE INSERT ON infection_control_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_restraint_assessments ON patient_restraint_assessments;
CREATE TRIGGER trg_set_facility_patient_restraint_assessments BEFORE INSERT ON patient_restraint_assessments
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_new_medication_prescriptions ON new_medication_prescriptions;
CREATE TRIGGER trg_set_facility_new_medication_prescriptions BEFORE INSERT ON new_medication_prescriptions
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_activity_records ON patient_activity_records;
CREATE TRIGGER trg_set_facility_patient_activity_records BEFORE INSERT ON patient_activity_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_care_tabs ON patient_care_tabs;
CREATE TRIGGER trg_set_facility_patient_care_tabs BEFORE INSERT ON patient_care_tabs
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_hospital_outreach_records ON hospital_outreach_records;
CREATE TRIGGER trg_set_facility_hospital_outreach_records BEFORE INSERT ON hospital_outreach_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_patient_evening_care_plans ON patient_evening_care_plans;
CREATE TRIGGER trg_set_facility_patient_evening_care_plans BEFORE INSERT ON patient_evening_care_plans
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

-- patient_id 可為 NULL：NULL 代表全院舍共用，facility_id 保持 NULL
DROP TRIGGER IF EXISTS trg_set_facility_medication_workflow_settings ON medication_workflow_settings;
CREATE TRIGGER trg_set_facility_medication_workflow_settings BEFORE INSERT ON medication_workflow_settings
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

DROP TRIGGER IF EXISTS trg_set_facility_restraint_observation_records ON restraint_observation_records;
CREATE TRIGGER trg_set_facility_restraint_observation_records BEFORE INSERT ON restraint_observation_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1).patient_id');

-- 院友欄位為中文「院友id」的表
DROP TRIGGER IF EXISTS trg_set_facility_health_monitoring_records ON "健康監測記錄";
CREATE TRIGGER trg_set_facility_health_monitoring_records BEFORE INSERT ON "健康監測記錄"
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1)."院友id"');

DROP TRIGGER IF EXISTS trg_set_facility_followup_appointments ON "覆診安排主表";
CREATE TRIGGER trg_set_facility_followup_appointments BEFORE INSERT ON "覆診安排主表"
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1)."院友id"');

DROP TRIGGER IF EXISTS trg_set_facility_doctor_visit_details ON "看診院友細項";
CREATE TRIGGER trg_set_facility_doctor_visit_details BEFORE INSERT ON "看診院友細項"
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1)."院友id"');

DROP TRIGGER IF EXISTS trg_set_facility_patient_contacts ON patient_contacts;
CREATE TRIGGER trg_set_facility_patient_contacts BEFORE INSERT ON patient_contacts
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1)."院友id"');

DROP TRIGGER IF EXISTS trg_set_facility_deleted_health_records ON deleted_health_records;
CREATE TRIGGER trg_set_facility_deleted_health_records BEFORE INSERT ON deleted_health_records
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('($1)."院友id"');

-- 經中間表連到院友的表
DROP TRIGGER IF EXISTS trg_set_facility_care_plan_problems ON care_plan_problems;
CREATE TRIGGER trg_set_facility_care_plan_problems BEFORE INSERT ON care_plan_problems
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('(SELECT patient_id FROM care_plans WHERE id = ($1).care_plan_id)');

DROP TRIGGER IF EXISTS trg_set_facility_care_plan_nursing_needs ON care_plan_nursing_needs;
CREATE TRIGGER trg_set_facility_care_plan_nursing_needs BEFORE INSERT ON care_plan_nursing_needs
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('(SELECT patient_id FROM care_plans WHERE id = ($1).care_plan_id)');

DROP TRIGGER IF EXISTS trg_set_facility_episode_events ON episode_events;
CREATE TRIGGER trg_set_facility_episode_events BEFORE INSERT ON episode_events
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('(SELECT patient_id FROM hospital_episodes WHERE id = ($1).episode_id)');

DROP TRIGGER IF EXISTS trg_set_facility_doctor_visit_reasons ON "到診院友_看診原因";
CREATE TRIGGER trg_set_facility_doctor_visit_reasons BEFORE INSERT ON "到診院友_看診原因"
  FOR EACH ROW EXECUTE FUNCTION set_facility_id_from_patient('(SELECT "院友id" FROM "看診院友細項" WHERE "細項id" = ($1)."細項id")');
